/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: 'BANK OF AI',
      className: 'sidebar-icon sidebar-icon-bankofai',
      collapsed: false,
      items: [
        'BANK-OF-AI/Intro',
        'BANK-OF-AI/QuickStart',
        {
          type: 'link',
          label: 'Official Website',
          href: 'https://bankofai.io/',
        },
        {
          type: 'link',
          label: 'GitHub',
          href: 'https://github.com/BofAI',
        },
      ],
    },
    {
      type: 'category',
      label: 'x402 Payment Protocol',
      className: 'sidebar-icon sidebar-icon-x402',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'x402/index',
          label: 'Introduction',
        },
        {
          type: 'category',
          label: 'Getting Started',
          collapsed: true,
          items: [
            'x402/getting-started/quickstart-for-sellers',
            {
              type: 'category',
              label: 'Quickstart for Buyers',
              collapsed: true,
              items: ['x402/getting-started/quickstart-for-human', 'x402/getting-started/quickstart-for-agent'],
            },
          ],
        },
        {
          type: 'category',
          label: 'Core Concepts',
          items: [
            'x402/core-concepts/http-402',
            'x402/core-concepts/client-server',
            'x402/core-concepts/facilitator',
            'x402/core-concepts/OfficialFacilitator',
            'x402/core-concepts/gateway',
            {
              type: 'category',
              label: 'API Catalog',
              collapsed: true,
              items: [
                'x402/api-catalog/index',
                'x402/api-catalog/get-started',
                'x402/api-catalog/list-your-service',
                'x402/api-catalog/reference',
              ],
            },
            'x402/core-concepts/wallet',
            'x402/core-concepts/network-and-token-support',
          ],
        },
        {
          type: 'doc',
          id: 'x402/sdk-features',
          label: 'SDK Features',
        },
        {
          type: 'category',
          label: 'x402 CLI',
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'x402/cli/index',
              label: 'Overview',
            },
            'x402/cli/quickstart',
            'x402/cli/command-reference',
            'x402/cli/faq',
          ],
        },
        {
          type: 'doc',
          id: 'x402/faq',
          label: 'FAQ',
        },
      ],
    },
    {
      type: 'category',
      label: 'SKILLS',
      className: 'sidebar-icon sidebar-icon-skills',
      collapsed: false,
      items: [
        'McpServer-Skills/SKILLS/Intro',
        'McpServer-Skills/SKILLS/QuickStart',
        'McpServer-Skills/SKILLS/BANKOFAISkill',
        'McpServer-Skills/SKILLS/Faq',
      ],
    },
    {
      type: 'category',
      label: 'Agent Wallet',
      className: 'sidebar-icon sidebar-icon-wallet',
      collapsed: true,
      items: [
        'Agent-Wallet/Intro',
        'Agent-Wallet/QuickStart',
        {
          type: 'category',
          label: 'Explore Further',
          collapsed: true,
          items: [
            'Agent-Wallet/Developer/CLI-Reference',
            'Agent-Wallet/Developer/SDK-Guide',
            'Agent-Wallet/Developer/SDK-Cookbook',
          ],
        },
        'Agent-Wallet/FAQ',
      ],
    },
    {
      type: 'category',
      label: 'LLM Service',
      className: 'sidebar-icon sidebar-icon-llm',
      collapsed: true,
      items: [
        { type: 'doc', id: 'llmservice/introduction', label: 'Introduction' },
        { type: 'doc', id: 'llmservice/quick-start', label: 'Quick Start' },
        { type: 'doc', id: 'llmservice/pricing-and-usage', label: 'Pricing and Usage' },
        {
          type: 'category',
          label: 'Models',
          collapsed: true,
          items: [
            'llmservice/models/gpt-5-mini',
            'llmservice/models/gpt-5-nano',
            'llmservice/models/gpt-5-2',
            'llmservice/models/gpt-5-6-sol',
            'llmservice/models/gpt-5-6-terra',
            'llmservice/models/gpt-5-6-luna',
            'llmservice/models/gpt-5-4',
            'llmservice/models/gpt-5-5',
            'llmservice/models/gpt-5-5-instant',
            'llmservice/models/gpt-5-4-mini',
            'llmservice/models/gpt-5-4-nano',
            'llmservice/models/gpt-5-4-pro',
            'llmservice/models/claude-haiku-4-5',
            'llmservice/models/claude-opus-4-5',
            'llmservice/models/claude-opus-4-6',
            'llmservice/models/claude-opus-4-7',
            'llmservice/models/claude-opus-4-8',
            'llmservice/models/claude-fable-5',
            'llmservice/models/claude-sonnet-5',
            'llmservice/models/claude-sonnet-4-5',
            'llmservice/models/claude-sonnet-4-6',
            'llmservice/models/deepseek-v3.2',
            'llmservice/models/deepseek-v4-pro',
            'llmservice/models/deepseek-v4-flash',
            'llmservice/models/gemini-3-1-pro',
            'llmservice/models/gemini-3-5-flash',
            'llmservice/models/gemini-3-flash',
            'llmservice/models/glm-5-2',
            'llmservice/models/glm-5-1',
            'llmservice/models/kimi-k3',
            'llmservice/models/kimi-k2.6',
            'llmservice/models/kimi-k2.5',
            'llmservice/models/qwen3.6-27b',
            'llmservice/models/minimax-m3',
            'llmservice/models/minimax-m2.7',
          ],
        },
        { type: 'doc', id: 'llmservice/memory', label: 'Memory' },
        {
          type: 'category',
          label: 'OpenClaw',
          collapsed: true,
          items: ['llmservice/openclaw/integration-guide', 'llmservice/openclaw/one-click-script-tutorial'],
        },
        {
          type: 'category',
          label: 'Claude Code',
          collapsed: true,
          items: ['llmservice/Claude-Code/claudecode-bankofai-api-configuration-guide'],
        },
        {
          type: 'category',
          label: 'API',
          collapsed: true,
          items: ['llmservice/api/API'],
        },
      ],
    },
    {
      type: 'category',
      label: 'MCP Server',
      className: 'sidebar-icon sidebar-icon-mcp',
      collapsed: true,
      items: [
        'McpServer-Skills/MCP/Intro',
        {
          type: 'category',
          label: 'TRON MCP Server',
          collapsed: true,
          items: [
            'McpServer-Skills/MCP/TRONMCPServer/Intro',
            'McpServer-Skills/MCP/TRONMCPServer/QuickStart',
            'McpServer-Skills/MCP/TRONMCPServer/OfficialServerAccess',
            'McpServer-Skills/MCP/TRONMCPServer/LocalPrivatizedDeployment',
            'McpServer-Skills/MCP/TRONMCPServer/ToolList',
            'McpServer-Skills/MCP/TRONMCPServer/FAQ',
          ],
        },
        {
          type: 'category',
          label: 'BSC MCP Server',
          collapsed: true,
          items: [
            'McpServer-Skills/MCP/BSCMCPServer/Intro',
            'McpServer-Skills/MCP/BSCMCPServer/Features',
            'McpServer-Skills/MCP/BSCMCPServer/Installation',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '8004 Protocol',
      className: 'sidebar-icon sidebar-icon-8004',
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: '8004/general',
          label: 'Introduction',
        },
        {
          type: 'doc',
          id: '8004/contract',
        },
        {
          type: 'doc',
          id: '8004/QuickStart',
        },
        {
          type: 'doc',
          id: '8004/SupportedNetworks',
        },
        {
          type: 'category',
          label: 'Usage',
          collapsed: true,
          items: ['8004/Usage/Install', '8004/Usage/ConfigureAgents', '8004/Usage/RegistrationHTTP'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Openclaw Extension',
      className: 'sidebar-icon sidebar-icon-openclaw',
      collapsed: true,
      items: ['Openclaw-extension/Intro', 'Openclaw-extension/QuickStart', 'Openclaw-extension/FAQ'],
    },
  ],
}

module.exports = sidebars
